name: Deploy Alpha

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Next.js app
        run: yarn run build

      - name: Linter
        run: yarn run lint

      - name: Type checking
        run: yarn run check-types

      - name: Install rsync and ssh-agent
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync
          sudo apt-get install -y openssh-client

      - name: Deploy to VPS
        env:
          PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_SSH_IP }}
          DEPLOY_USER: ${{ secrets.DEPLOY_SSH_USER }}
        run: |
          echo "$PRIVATE_KEY" | base64 --decode > private_key.pem
          chmod 600 private_key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts
          echo "Host $DEPLOY_HOST" > ~/.ssh/config
          echo "  IdentityFile $(pwd)/private_key.pem" >> ~/.ssh/config
          rsync -avz --delete --exclude-from=.deployignore ./ $DEPLOY_USER@$DEPLOY_HOST:/home/$DEPLOY_USER/www/boooki-alpha
          ssh $DEPLOY_USER@$DEPLOY_HOST "cd /home/$DEPLOY_USER/www/boooki-alpha && yarn install --frozen-lockfile && NODE_ENV=alpha pm2 restart boooki-alpha"
          rm -f private_key.pem
