name: Deploy Alpha

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Linter
        run: npm run lint

      - name: Type checking
        run: npm run check-types

      - name: Install rsync and ssh-agent
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync
          sudo apt-get install -y openssh-client

      - name: Deploy to VPS
        env:
          PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_SSH_IP }}
          DEPLOY_USER: ${{ secrets.DEPLOY_SSH_USER }}
        run: |
          echo "$PRIVATE_KEY" | base64 --decode > private_key.pem
          chmod 600 private_key.pem
          mkdir -p ~/.ssh
          echo "Host $DEPLOY_HOST" > ~/.ssh/config
          echo "  IdentityFile $(pwd)/private_key.pem" >> ~/.ssh/config
          rsync -avz --delete --exclude-from=.deployignore ./ $DEPLOY_USER@$DEPLOY_HOST:/www/boooki-alpha
          ssh $DEPLOY_USER@$DEPLOY_HOST "cd /www/boooki-alpha && npm ci && NODE_ENV=alpha pm2 restart boooki-alpha"
          rm -f private_key.pem
